controllers/SiteController.php
<?php
namespace xing\ace\controllers;

use xing\ace\models\Menu;
use xing\ace\helper\Tree;
use xing\ace\logic\AdminRuleLogic;
use xing\ace\models\AdminRole;
use xing\ace\models\AdminRule;
use xing\ace\models\ChangeForm;
use xing\ace\models\AdminUser;
use xing\helper\yii\ReturnHelper;
use Yii;
use yii\base\InvalidParamException;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use xing\ace\models\LoginForm;
use xing\ace\models\PasswordResetRequestForm;
use xing\ace\models\ResetPasswordForm;
use xing\ace\models\SignupForm;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    public $layout = false;
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'user'  => ArrayHelper::getValue($this->module, 'user'),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow'   => true,
                    ],
                    [
                        'actions' => [
                            'logout', 'index', 'system',
                            'update', 'create', 'switch-login',
                        ],
                        'allow'   => true,
                        'roles'   => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
//        $this->layout = false;
        $menu = AdminRuleLogic::getNav(Yii::$app->user->identity->role_id);
//        $menu = AdminRole::buildNav($menu);
        return $this->render('index',['menu' => $menu]);
    }

    /**
     * 显示首页系统信息
     *
     * @return string
     */
    public function actionSystem()
    {
        // 获取用户信息
        return $this->render('system', [
            'yii'    => Yii::getVersion(),                         // Yii 版本
            'upload' => ini_get('upload_max_filesize'),             // 上传文件大小,
            'user'   => Yii::$app->user->identity,
        ]);
    }
    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $this->layout = 'login';

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            switch ($_SERVER['HTTP_REQUEST_TYPE'] ?? null) {
                case 'api':
                    return ReturnHelper::returnData(['access_token' => $model->login()], 'ok');
                default:
                    return $this->goBack();
            }
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
//    public function actionSignup()
//    {
//        $model = new SignupForm();
//        if ($model->load(Yii::$app->request->post())) {
//            if ($user = $model->signup()) {
//                if (Yii::$app->getUser()->login($user)) {
//                    return $this->goHome();
//                }
//            }
//        }
//
//        return $this->render('signup', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionChangePass()
    {
        $model = new ChangeForm();
        if($model->load(Yii::$app->request->post()))
        {
            $user = AdminUser::getByPK(Yii::$app->user->id);
            if((md5($model->original) === $user->password))
            {
                if($model->validate())
                {
                    $user->password = md5($model->password);
                    if($user->save())
                        return $this->render('success');
                }
            }
            else
                $model->addError('original', '原密码错误');
        }

        return $this->render('change', ['model'=>$model]);
    }
}

views/site/error.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="error-container">
    <div class="well">
        <h1 class="grey lighter smaller">
            <span class="blue bigger-125">
                <i class="ace-icon fa fa-sitemap"></i>
                <?= Html::encode($this->title) ?>
            </span>
            <?= nl2br(Html::encode($message)) ?>
        </h1>
        <hr />
        <div class="alert alert-danger">
            <?= nl2br(Html::encode($message)) ?>
        </div>
        <h3 class="lighter smaller"><?= nl2br(Html::encode($message)) ?></h3>
        <div>


            <div class="space"></div>
            <h4 class="smaller">尝试下列方法：</h4>

            <ul class="list-unstyled spaced inline bigger-110 margin-15">
                <li>
                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                    告诉管理员添加权限操作
                </li>
                <li>
                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                    阅读常见问题
                </li>
                <li>
                    <i class="ace-icon fa fa-hand-o-right blue"></i>
                    告诉我们
                </li>
            </ul>
        </div>

        <hr />
        <div class="space"></div>
        <div class="center">
            <a href="javascript:history.back()" class="btn btn-grey">
                <i class="ace-icon fa fa-arrow-left"></i>
                回去
            </a>

            <a href="javascript: window.parent ? window.parent.location.reload() : window.location.href = '<?=Url::to(['site/system'])?>'" class="btn btn-primary">
                <i class="ace-icon fa fa-desktop"></i>
                首页
            </a>
        </div>
    </div>
</div>

views/site/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model xing\ace\models\LoginForm */

$this->title = Yii::t('admin', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $form = ActiveForm::begin(); ?>
<fieldset>
    <label class="block clearfix">
        <span class="block input-icon input-icon-right">
            <?= $form->field($model, 'username')->textInput(['placeholder' => $model->getAttributeLabel('username')])->label(false) ?>
            <i class="ace-icon fa fa-user"></i>
        </span>
    </label>

    <label class="block clearfix">
        <span class="block input-icon input-icon-right">
            <?= $form->field($model, 'password')->passwordInput(['placeholder' => $model->getAttributeLabel('password')])->label(false) ?>
            <i class="ace-icon fa fa-lock"></i>
        </span>
    </label>
    <div class="space"></div>
    <div class="clearfix">
        <label class="inline">
            <?= $form->field($model, 'rememberMe')->checkbox() ?>
        </label>
        <?= Html::submitButton('登录', ['class' => 'btn bg-olive btn-block width-35 pull-right btn btn-sm btn-primary']) ?>
    </div>
    <div class="space-4"></div>
</fieldset>
<?php ActiveForm::end(); ?>

views/site/system.php
<?php

use yii\helpers\ArrayHelper;
$this->title = '登录信息';
?>
<div class="row">
    <div class="col-xs-12 col-sm-12 text-center">
        <h4 class="blue">
            <span class="middle"><i class="ace-icon glyphicon glyphicon-user light-blue bigger-110"></i></span>
            欢迎登陆后台管理系统
        </h4>
        <div class="profile-user-info">
            <div class="profile-info-row">
                <div class="profile-info-name"> 账号</div>
                <div class="profile-info-value">
                    <span><?= $user->username ?></span>
                </div>
            </div>
            <!--<div class="profile-info-row">
                <div class="profile-info-name"> 角色</div>
                <div class="profile-info-value">
                    <span>
                        <?php
/*                        $roles = Yii::$app->authManager->getRolesByUser($user->id);
                        echo implode(',', array_keys($roles));
                        */?>
                    </span>
                </div>
            </div>-->
        </div>
        <div class="hr hr16 dotted"></div>
        <?php if (ArrayHelper::getValue(Yii::$app->params, 'project_open_other')) : ?>
            <h4 class="blue">
                <span class="middle"><i class="fa fa-desktop light-blue bigger-110"></i></span>
                其他信息
            </h4>

            <div class="profile-user-info">
                <div class="profile-info-row">
                    <div class="profile-info-name"> 版本</div>
                    <div class="profile-info-value">
                        <span><?= $yii ?></span>
                    </div>
                </div>

                <div class="profile-info-row">
                    <div class="profile-info-name"> 上传文件</div>
                    <div class="profile-info-value">
                        <span><?= $upload ?></span>
                    </div>
                </div>
            </div>
            <div class="hr hr-8 dotted"></div>
            <div class="profile-user-info">
                <div class="profile-info-row">
                    <div class="profile-info-name">
                        <i class="fa fa-github-square" aria-hidden="true"></i>
                        GitHub
                    </div>
                    <div class="profile-info-value">
                        <a href="https://github.com/myloveGy" target="_blank">https://github.com/aa0604</a>
                    </div>
                </div>
            </div>

            <div class="hr hr16 dotted"></div>
        <?php endif; ?>
    </div>
</div>