models/AdminRole.php
<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2016/12/10 15:43
// +----------------------------------------------------------------------
// | TITLE: 角色
// +----------------------------------------------------------------------


namespace xing\ace\models;


use yii\helpers\Url;

class AdminRole extends BaseActiveModel
{
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    /**
     * 超级管理员分组
     */
    const ADMIN_ID = 1;

    public static $statusList = [
        1 => '开启',
        0 => '关闭',
    ];

    public static function tableName()
    {
        return 'admin_role';
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_CREATE] = ['code', 'name', 'create_date', 'des','rule'];
        $scenarios[self::SCENARIO_UPDATE] = ['code', 'name', 'update_user', 'des', 'update_date', 'rule'];
        return $scenarios;

    }


    public function rules()
    {
        return [
            ['code', 'required', 'message' => '编号必须'],
            ['name', 'required', 'message' => '名称必须'],
            [['create_date', 'update_date'], 'safe'],
            ['update_date', 'default', 'value' => self::getDate()],
            ['create_date', 'default', 'value' => self::getDate()],
            [['code', 'name', 'create_user', 'update_user'], 'string', 'max' => 50],
            [['des'], 'string', 'max' => 400],
            ['rule', 'string',]
        ];

    }

    public function attributeLabels()
    {
        return [
            'id' => '主键',
            'code' => '角色编号',
            'name' => '角色名称',
            'des' => '角色描述',
            'create_user' => '创建人',
            'create_date' => '创建时间',
            'update_user' => '更新人',
            'update_date' => '更新时间',
            'rule' => '权限',
            'status' => '状态',
        ];
    }

    public static function getDate()
    {
        return date('Y-m-d H:i:s');
    }

    /**
     * 转换状态
     * @param $status
     * @return mixed
     */
    public static function status_to_str($status)
    {
        return self::$statusList[$status];
    }

    /**
     * 删除角色
     * @param $id
     * @return bool
     */
    public static function deleteRole($id)
    {
        $model = self::findOne($id);
        if ($model) {
            $model->status = 0;
            $model->save();
            return true;
        } else {
            return false;
        }
    }

    /**
     * 获取权限
     * @param int $id 用户角色
     * @param int $type 查询类型，1：所有类型权限，2只列出菜单权限
     * @return array|\yii\db\ActiveRecord[]
     */
    public static function getRule($id,$type = '1')
    {
        $AdminRule = AdminRule::find();
        $AdminRule->where(['status' => 1]);
        $AdminRule->andWhere(['is_show' => 1]);
        $AdminRule->orderBy('order Asc');
        if ($type == '2'){ //如果是查询菜单，只列出权限菜单
            $AdminRule->andWhere(['in', 'type', [1,3]]);
        }
        if (self::ADMIN_ID != $id) {
            //更改用戶角色可以多选
            $ruleAll = AdminRole::find()->select('rule')->andWhere(['in','id',explode(',',$id)])->createCommand()->queryAll();
            $rule = implode(',',array_column($ruleAll,'rule'));
            $rule = explode(',',$rule);
            $AdminRule->andWhere(['in', 'id', $rule]);
//            echo $AdminRule->createCommand()->getRawSql();
//            die();
        }
        return $AdminRule->asArray()->all();
    }


    /**
     * 生成
     * @param $data
     * @param string $html
     * @return string
     */
    public static function buildMenuHtml($data, $html = '')
    {
        if (empty($data)){
            return "";
        }
        foreach ($data as $k => $v) {
            if (isset($v['type']) && $v['type'] != 2 && $v['status'] == 1) {

                $html .= '<li >';
                //需要验证是否有子菜单
                if (isset($v['children']) && is_array($v['children'])) {
                    $html .= '<a href="javascript::(0)" class="dropdown-toggle">';
                } else {
                    $html .= '<a href="javascript:openapp(\' ' . Url::toRoute($v['route']) . '\',\'' . $v['id'] . '\',\'' . $v['title'] . '\',true);" class="">';
                }
                //图标
                $html .= '<i class="menu-icon ' . $v['icon'] . '"></i>';
                //名称
                $html .= '   <span class="menu-text">' . $v['title'] . '</span>';

                if (isset($v['children']) && is_array($v['children'])) {
                    $html .= '<b class="arrow fa fa-angle-down"></b></a>';
                } else {
                    $html .= '<b class="arrow fa s"></b></a>';
                }

                //需要验证是否有子菜单
                if (isset($v['children']) && is_array($v['children'])) {
                    $html .= ' <b class="arrow"></b>';
                    $html .= '<ul class="submenu nav-hide" style="display: none;">';
                    $html .= self::buildMenuHtml($v['children']);
                    //验证是否有子订单
                    $html .= '</ul>';
                }
                $html .= '</li>';
            }
        }
        return $html;

    }

    public static function buildNav($list)
    {
        er($list);
        foreach ($list as $v) {

        }
    }
}

controllers/AdminRoleController.php
<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2016/12/13 22:10
// +----------------------------------------------------------------------
// | TITLE: 角色
// +----------------------------------------------------------------------

namespace xing\ace\controllers;

use xing\ace\helper\Tree;
use xing\ace\models\AdminRule;
use Yii;
use xing\ace\models\AdminRole;
use yii\web\Response;

class AdminRoleController extends BaseController
{


    /**
     * 角色列表
     * @return string
     */
    public function actionIndex()
    {
        $AdminRole = AdminRole::find();
        $models = $AdminRole->where(['status' => 1])->all();
        return $this->render('index', ['model' => $models]);
    }

    /**
     * 创建角色
     * @return array|string
     */
    public function actionCreate()
    {
        $AdminRole = new AdminRole(['scenario' => 'create']);
        if (Yii::$app->request->isPost){
            Yii::$app->response->format = Response::FORMAT_JSON;
            $data = Yii::$app->request->post('AdminRole');
            $name = $data['name'];
            if(empty($name))
            {
                return ['code' => 400, 'message' => '角色名称不得为空'];
            }
            $Info = $AdminRole::find()->where("name='$name'")->one();
            if(!empty($Info))
            {
                return ['code' => 400, 'message' => '角色名称已存在'];
            }
            if ($AdminRole->load(Yii::$app->request->post()) && $AdminRole->validate()) {
                if ($AdminRole->save()) {
                    return ['code' => 200, 'message' => '添加成功'];
                } else {
                    return ['code' => 400, 'message' => array_values($AdminRole->getFirstErrors())[0]];
                }
            }else{
                return ['code' => 400, 'message' => array_values($AdminRole->getFirstErrors())[0]];
            }
        }  else {
            $ruleAll = AdminRule::find()->where(['status' => 1])->asArray()->all();
            $arr = [];
            foreach ($ruleAll as $k=>$v){
                $tmp = ['id'=>$v['id'],'pId'=>$v['pid'],'name'=>$v['title'],'open'=>true];
                array_push($arr,$tmp);
            }
            return $this->render('create', ['ruleAll' => json_encode($arr)]);
        }

    }

    /**
     * 更新角色
     * @return array|string
     */
    public function actionUpdate()
    {
        $id = Yii::$app->request->get('id');
        $model = AdminRole::findOne($id);
        $model->scenarios('update');
        if (Yii::$app->request->isPost){
            Yii::$app->response->format = Response::FORMAT_JSON;
            $data = Yii::$app->request->post('AdminRole');
            if(empty($data['name']))
            {
                return ['code' => 400, 'message' => '角色名称不得为空'];
            }
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                if ($model->save()) {
                    return ['code' => 200, 'message' => '修改成功'];
                } else {
                    return ['code' => 400, 'message' => array_values($model->getFirstErrors())[0]];
                }
            }else{
                return ['code' => 400, 'message' => array_values($model->getFirstErrors())[0]];
            }
        }  else {
            $myRole = explode(',',$model->rule);
            $ruleAll = AdminRule::find()->where(['status' => 1])->asArray()->all();
            $arr = [];
            foreach ($ruleAll as $k=>$v){
                $checked = in_array($v['id'],$myRole) ? "true": "false";
                $tmp = ['id'=>$v['id'],'pId'=>$v['pid'],'name'=>$v['title'],'open'=>true,'checked'=>$checked];
                array_push($arr,$tmp);
            }
            return $this->render('update', ['model' => $model,'ruleAll'=> json_encode($arr)]);
        }
    }

    /**
     * 删除 角色
     * @return array
     */
    public function actionDelete()
    {
        $id = Yii::$app->request->get('id');
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (AdminRole::deleteRole($id)) {
            return ['code' => 200, 'message' => '成功'];
        } else {
            return ['code' => 400, 'message' => '错误'];
        }
    }

    /**
     * 设置权限
     * @return array|string
     */
    public function actionSetRule()
    {

        $roleId = Yii::$app->request->get('id');
        if (empty($roleId)) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['code' => 400, 'message' => '参数错误'];
        }
        $model = AdminRole::findOne($roleId);
        $model->rule = explode(',', $model->rule);
        if (Yii::$app->request->post()) {
            $rule = Yii::$app->request->post('rule');
            $rule = array_filter($rule);
            krsort($rule);
            $rule = implode(',', $rule);
            $model->scenario = 'update';
            $model->rule = $rule;
            Yii::$app->response->format = Response::FORMAT_JSON;
            if (!$model->save()) {
                return ['code' => 400, 'message' => '修改失败'];
            } else {
                return ['code' => 200, 'message' => '修改成功'];
            }

        } else {
            $ruleAll = AdminRule::find()->where(['status' => 1])->asArray()->all();
            $ruleAll = array_map(function ($item) use ($model) {
                (in_array($item['id'], $model->rule)) ?
                    $item['state'] = ['checked' => true] : '';
                $item['text'] = $item['title'];
                return $item;
            }, $ruleAll);
            $ruleAll = Tree::makeTree($ruleAll, ['children_key' => 'nodes']);
            return $this->render('setRule2', ['ruleAll' => $ruleAll, 'model' => $model]);
        }

    }



}

views/admin-role/create.php
<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2016/12/13 22:25
// +----------------------------------------------------------------------
// | TITLE: 创建角色
// +----------------------------------------------------------------------
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\tools\Tool;
\xing\ace\AdminRoleAsset::register($this);
?>

<?php $this->beginBlock('head'); ?>

<?php $this->endBlock(); ?>
    <!--===========================================-->
    <!--html-->
    <div class="main-container" id="main-container">
        <!-- /section:basics/sidebar -->
        <div class="main-content">
            <div class="main-content-inner">
                <div class="page-content">
                    <div class="page-header">
                        <h1>
                            角色
                            <small>
                                <i class="ace-icon fa fa-angle-double-right"></i>
                                添加角色
                            </small>
                        </h1>
                    </div><!-- /.page-header -->

                    <div class="row">
                        <a href="<?=  Url::toRoute('admin-role/index')?>" class="btn btn-primary">
                            <i class="icon-only ace-icon fa fa-align-left"></i>
                            列表
                        </a>
                    </div>
                    <div class="hr hr-18 dotted hr-double"></div>

                    <div class="row">
                        <div class="col-xs-12">
                            <!-- PAGE CONTENT BEGINS -->
                            <?php $form =  ActiveForm::begin(
                                ['id' => 'admin-role-form',
                                    'action'=>Url::toRoute('admin-role/create'),
                                    'enableAjaxValidation' => true,
                                ])?>
                                <!-- #section:elements.form -->
                                <div class="row form-horizontal">

                                    <div class="col-xs-10 col-lg-offset-1">
                                        <div class="widget-box">
                                            <div class="widget-header">
                                                <h4 class="widget-title">添加角色</h4>
                                            </div>

                                            <div class="widget-body">
                                                <div class="widget-main">
                                                    <div class="form-group field-form-field-1 required">
                                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1">*角色名称:</label>
                                                        <input id="form-field-1" class="col-md-offset-1  col-sm-3" name="AdminRole[name]" placeholder="角色名称" aria-required="true" type="text">
                                                        <div class="help-block"></div>
                                                    </div>
                                                    <div class="form-group field-form-field-1 required" >
                                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1">*选择权限:</label>
                                                        <div class="col-md-offset-1  col-sm-3">
                                                            <ul id="treeDemo" class="ztree"  style="height:400px;"></ul>
                                                        </div>
                                                    </div>
                                                    <div class="form-group field-form-field-1 required"  style="display: none">
                                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1">*角色编号:</label>
                                                        <input id="form-field-1" class="col-md-offset-1  col-sm-3" name="AdminRole[code]" value="<?=date('YmdHis')?>" readonly="readonly" placeholder="角色编号" aria-required="true" type="text">

                                                        <div class="help-block"></div>
                                                    </div>
                                                    <div class="form-group field-form-field-1" style="display: none">
                                                        <label class="col-sm-3 control-label no-padding-right" for="form-field-1">描述:</label>
                                                        <input id="form-field-1" class="col-md-offset-1  col-sm-3" name="AdminRole[des]" placeholder="描述" type="text">

                                                        <div class="help-block"></div>
                                                    </div>
                                                    <div class="clearfix ">
                                                        <div class="col-md-offset-3 col-md-9">
                                                            <button class="btn btn-info ajaxForm" type="button">
                                                                <i class="ace-icon fa fa-check bigger-110"></i>
                                                                提交
                                                            </button>&nbsp;
                                                            <button class="btn" type="reset">
                                                                <i class="ace-icon fa fa-undo bigger-110"></i>
                                                                重置
                                                            </button>
                                                        </div>
                                                    </div>

                                                    <div class="hr hr-24"></div>
                                                </div>


                                            </div>
                                        </div>
                                    </div><!-- /.span -->
                                </div><!-- /.row -->
                            <?php ActiveForm::end();?>

                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.page-content -->
            </div>
        </div><!-- /.main-content -->


    </div><!-- /.main-container -->
    <!--html-->
    <!--===========================================-->
<?php $this->beginBlock('footer'); ?>

<?php $this->endBlock(); ?>

<script>

    var zNodes = <?= $ruleAll ?>;
</script>
<?php
$js = <<<JAVASCRIP

    var setting = {
        check: {
            enable: true
        },
        data: {
            simpleData: {
                enable: true
            }
        },
        callback:{
            //onCheck:onCheck
        }

    };

    $(document).ready(function(){
        $.fn.zTree.init($("#treeDemo"), setting, zNodes);

    });
    //获取选中数据
    function onCheck(){
        var treeObj=$.fn.zTree.getZTreeObj("treeDemo"),
            nodes=treeObj.getCheckedNodes(true),
            v="";
        for(var i=0;i<nodes.length;i++){
            v += nodes[i].id + ","; //获取name值
        }
        return v; //获取选中节点的值
    }

    //提交数据
    $('.ajaxForm').bind('click',function () {
        var s = onCheck();
        if (s  == ""){
            alert_err("权限不得为空！");
            return false;
        }

        var data = {};
        data['AdminRole[name]'] = $("input[name='AdminRole[name]']").val();
        data['AdminRole[code]'] = $("input[name='AdminRole[code]']").val();
        data['AdminRole[rule]'] = s.substring(0,s.length-1);
        ajaxPullData(data,'/admin/admin-role/create',function (data) {
            if (data.code == 200 ){
                alert_succ(data.message,function () {
                    window.location.href = '/admin/admin-role/index';
                })
            }else{
                alert_err(data.message);
            }
        })

        
    });
JAVASCRIP;

$this->registerJs($js);
?>

views/admin-role/index.php
<?php
use yii\helpers\Url;
use xing\ace\models\AdminRole;

$AdminRole  = new \xing\ace\models\AdminRole;
?>


<!-- /section:basics/navbar.layout -->
<div class="main-container" id="main-container">

    <!-- /section:basics/sidebar -->
    <div class="main-content">
        <div class="main-content-inner">

            <!-- /section:basics/content.breadcrumbs -->
            <div class="page-content">

                <!-- /section:settings.box -->
                <div class="page-header">
                    <h1>
                        角色管理
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                           角色列表
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <a href="<?=  Url::toRoute('admin-role/create')?>" class="btn">
                        <i class="ace-icon fa fa-pencil align-top bigger-125"></i>
                        新增
                    </a>

                </div>

                <div class="hr hr-18 dotted hr-double"></div>

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="row">
                            <div class="col-xs-12">
                                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>

                                        <th><?=$AdminRole->getAttributeLabel('id')?></th>
                                        <th><?=$AdminRole->getAttributeLabel('name')?></th>

                                        <th style="width: 50%;">
                                          权限
                                        </th>
                                        <th class="hidden-480">  <?=$AdminRole->getAttributeLabel('status')?></th>

                                        <th>操作</th>
                                    </tr>
                                    </thead>

                                    <tbody>

                                    <?php
                                    foreach ( $model as $k=>$v){

                                        if ($v['rule']){
                                            $list = \xing\ace\models\AdminRule::find()->where(['in', 'id', $v['rule']])->asArray()->all();
                                            $role = implode(',', array_column($list, 'title'));
                                        }else{
                                           $role = "超级管理员";
                                        }

                                        echo  '<tr>';
                                        echo   '<td><a href="#">'.$v->id.'</a></td>';
                                        echo    '<td>'.$v->name.'</td>';
                                        echo    '<td>'.$role.'</td>';
                                        echo    '<td>'.AdminRole::status_to_str($v->status ) .'</td>';
                                        echo    '<td>';
                                        if ($v->id != 1 ){
                                            echo   ' 
                                            <div class="inline position-relative">
                                                            <a href="'.Url::to(['admin-role/update','id'=>$v->id]).'" class="tooltip-success" data-rel="tooltip" title="Edit">
																			<span class="green">
																				<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
																				修改
																			</span>
                                                            </a>
                                                            <a data-id="'.$v->id.'" data-url="'.Url::to(['admin-role/delete','id'=>$v->id]).'"  class="tooltip-error delete" data-rel="tooltip" title="Delete">
																			<span class="red">
																				<i class="ace-icon fa fa-trash-o bigger-120"></i>
																				删除
																			</span>
                                                            </a>
                                                </div>
                                        ';
                                        }
                                        echo '</td>';

                                        echo ' </tr>';

                                    }

                                    ?>
                                    </tbody>
                                </table>
                            </div><!-- /.span -->
                        </div><!-- /.row -->

                        <div class="hr hr-18 dotted hr-double"></div>

                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->




</div><!-- /.main-container -->

<?php
$js = <<<JAVASCRIP

    $('.delete').bind('click',function () {
        var id= $(this).attr('data-id');
        var url= $(this).attr('data-url');
       alert_confirm('确定删除？',function () {
           $.get(url, function(data) {
               if(data.code == 200){
                   alert('删除成功');
                   window.location=location.href;
               }
           });
       })
    })
JAVASCRIP;

$this->registerJs($js);
?>

views/admin-role/setRule.php
<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2016/12/13 22:25
// +----------------------------------------------------------------------
// | TITLE: 设置权限
// +----------------------------------------------------------------------
use yii\helpers\Url;


$AdminRole = new \xing\ace\models\AdminRole;
use yii\bootstrap\ActiveForm;
?>


<!-- /section:basics/navbar.layout -->
<div class="main-container" id="main-container">

    <!-- /section:basics/sidebar -->
    <div class="main-content">
        <div class="main-content-inner">

            <!-- /section:basics/content.breadcrumbs -->
            <div class="page-content">

                <!-- /section:settings.box -->
                <div class="page-header">
                    <h1>
                        角色管理
                        <small>
                            <i class="ace-icon fa fa-angle-double-right"></i>
                            设置权限
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">

                    <div class="col-sm-8">
                        <h2>设置权限</h2>
                        <div id="treeview-checkable" class=""></div>
                    </div>
                </div>
                <div class="row">
                    <div class="clearfix ">
                        <div class="col-md-offset-3 col-md-9">
                            <button class="btn btn-info ajaxForm" type="button">
                                <i class="ace-icon fa fa-check bigger-110"></i>
                                确定
                            </button>&nbsp;
                        </div>
                    </div>
                </div>
                <?php $form =  ActiveForm::begin(
                    ['id' => 'setRule',
                        'action'=>Url::to(['set-rule','id'=>$model->id]),
                        'enableAjaxValidation' => true,
                    ])?>
                <?php ActiveForm::end();?>


            </div><!-- /.page-content -->
        </div>
    </div><!-- /.main-content -->


</div><!-- /.main-container -->
<?php $this->beginBlock('footer'); ?>

<!-- 增加的js -->
<script src="<?= Url::base() ?>/aceAdmin/assets/tree/src/js/bootstrap-treeview.js" type="text/javascript" charset="utf-8"></script>

<script>
    var defaultData = <?php echo json_encode($ruleAll)?>;
    var rule = <?php echo json_encode($model->rule);?>;
</script>

<?php
$js = <<<JAVASCRIP

    $(function() {
        //权限
        var $checkableTree = $('#treeview-checkable').treeview({
            data: defaultData,
            showIcon: false,
            showCheckbox: true,
            onNodeChecked: function(event, node) {
                rule.push( node.id)
            },
            onNodeUnchecked: function (event, node) {
                delete  rule[ $.inArray(node.id, rule)]
            }
        });


        /**
         *改变路由
         */
        function changeRule() {
            var data = Object();
            data._csrf=$('input[name=_csrf]').val();
            data.rule= rule;
            $.ajax({
                url:$('#setRule').attr('action'),
                type:'post',
                dataType:'json',
                data:data,
                success:function (data) {
                    if (data.code == 200){
                        alert_succ(data.message,function () {
                            window.location.href = "<?= Url::toRoute('/admin-role/index')?>"
                        });
                    }else {
                        alert_err(data.message);
                    }
                }
            })
        }
        $('.ajaxForm').bind('click',function () {
            changeRule();
        })

    });
JAVASCRIP;

$this->registerJs($js);
?>

<script type="text/javascript">

</script>
<?php $this->endBlock(); ?>